export enum LeadOrigin {
  INSTAGRAM = 'INSTAGRAM',
  LINKEDIN = 'LINKEDIN',
  GOOGLE = 'GOOGLE',
  INDICACAO = 'INDICACAO',
  SITE = 'SITE',
  EVENTO = 'EVENTO',
  WHATSAPP = 'WHATSAPP',
  OUTRO = 'OUTRO',
}
